//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SXHP_HengJiuGame_WenJH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRole
    {
        public System.Guid ID { get; set; }
        public System.Guid GameID { get; set; }
        public string RoleName { get; set; }
        public string Lines { get; set; }
        public string RoleType { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> ShelfTime { get; set; }
        public string Remark { get; set; }
    }
}
