//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SXHP_HengJiuGame_WenJH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public System.Guid ID { get; set; }
        public string UserName { get; set; }
        public string UserCode { get; set; }
        public string PassWord { get; set; }
        public Nullable<bool> sex { get; set; }
        public string Native { get; set; }
        public string IDCard { get; set; }
        public string Email { get; set; }
        public string TelPhone { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Dimission { get; set; }
        public Nullable<System.Guid> JobID { get; set; }
        public Nullable<System.Guid> StructureID { get; set; }
    }
}
